/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 *
 * clang++ p2.cc && ./a.out
 */

#include <iostream>

int FindSolution() {
  int first = 0;
  int second = 1;

  int sum = 0;
  while (second <= 4000000) {
  	int temp = first + second;
  	first = second;
  	second = temp;
  	sum += second % 2 == 0 ? second : 0;
  }

  return sum;
}

int main(int argc, char** argv) {
  std::cout << "Solution: " << FindSolution() << std::endl;

  return 0;
}
